GHCR image push- tfc-bacckup-b2
silinternational/tfc-backup-b2 pull request #7
Opened 2024-10-04 09:23 UTC by Praveenraj-K

-Pushing the images in both Docker Hub & GitHub Container Registry "GHCR.io"
-Only initiate when there is a commit in the main branch using the workflow trigger.

2024-10-04 11:31 UTC, devon-sil commented
@Praveenraj-K Thanks for putting together a PR for this. I've added the developers for review.

2024-10-07 04:29 UTC, hobbitronics approved these changes
Looks good to me!

2024-10-07 05:47 UTC, Praveenraj-K commented
Thanks Mike :)

2024-10-07 06:27 UTC, briskt requested changes

2024-10-07 06:27 UTC, briskt commented on .github/workflows/build-and-publish.yml
> +            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/develop' }}  # Tag as 'latest' if it's the 'develop' branch
```suggestion
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}  # Tag as 'latest' if it's the 'main' branch
```
Looks like it was an intentional change from main to develop, but I think we want to keep latest pointing to main. Let me know if I missed something.

2024-10-07 06:28 UTC, briskt commented on .github/workflows/build-and-publish.yml
> +            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/develop' }}  # Tag as 'latest' if it's the 'develop' branch
Or just remove `latest` altogether. I don't like the `latest` tag anyway.

2024-10-07 06:43 UTC, briskt commented on .github/workflows/build-and-publish.yml
> +    tags: [ 'v*.*.*' ]
If you want to restrict tag format, you need to use a regular expression like this:
```suggestion
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]
```
But better not to restrict it for now, I think.

2024-10-07 06:47 UTC, briskt commented on .github/workflows/build-and-publish.yml
> +    tags: [ 'v*.*.*' ]
Hmm, I'm not 100% sure it fully supports regular expressions. Maybe just the character set works. Here are examples: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#patterns-to-match-branches-and-tags

2024-10-07 06:48 UTC, briskt commented on .github/workflows/build-and-publish.yml
> +    tags: [ 'v*.*.*' ]
Yeah, if it did the `.` characters would have to be escaped. Oh well, like I said, better to just keep it simple for now.

2024-10-07 09:28 UTC, closed without merging